name: manual trigger

on: 
 workflow_dispatch:
  inputs:
   name:
    description: "who to greet"
    default: "world"
     
jobs:
 hello:
  runs-on: ubuntu-latest
   steps:
   - name: hello1
       run: echo "hello ${{ github.event.inputs.name}}"
